#ifndef __ASM_OFFSETS_H__
#define __ASM_OFFSETS_H__
/*
 * DO NOT MODIFY.
 *
 * This file was generated by Kbuild
 *
 */

#define ECTX_SIZE 288 /* sizeof(struct econtext) */
#define CTX_SIZE 272 /* sizeof(struct context) */
#define GP_REGS_SIZE 248 /* sizeof(struct gp_regs) */
#define PROC_STACK_OFFSET 80 /* offsetof(struct proc, stack_base) */
#define PROC_PAGETABLE_OFFSET 72 /* offsetof(struct proc, pagetable) */
#define PCPU_STACK_OFFSET 152 /* offsetof(struct cpu, intr_stack) */

#endif
