#pragma once


enum {
  OS_EVENT_TYPE_NORMAL,
  OS_EVENT_TYPE_MBOX,
  OS_EVENT_TYPE_QUEUE,
  OS_EVENT_TYPE_SEM,
  OS_EVENT_TYPE_MUTEX,
  OS_EVENT_TYPE_FLAG,
  OS_EVENT_TYPE_FUTEX,
  OS_EVENT_TYPE_IRQ,
  OS_EVENT_TYPE_POLL,
  OS_EVENT_TYPE_MAX,
  OS_EVENT_TYPE_TIMER,
};
